name: Build

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Tanks ${{ github.ref_name }}

  build:
    needs:
      - create-release
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PA_TOKEN }}

      - name: Set Up Python With Cache
        uses: actions/setup-python@v5
        with:
          cache: pip
      - name: Install Python Dependencies
        run: pip install -r requirements.lock

      - name: Cache Pyinstaller Files
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-pyinstaller

      - name: Build Binary
        run: pyinstaller tanks/main.py --onefile --noconsole --name tanks-${{ runner.os }} --add-data tanks/assets:tanks/assets

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: dist/tanks*
